<?php

namespace Container6uE3EtC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_C5e6NjjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.C5e6Njj' shared service.
     *
     * @return \App\Controller\ClientsAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\ClientController::cleanDatabases()": the $authenticator argument is type-hinted with the non-existent class or interface: "App\\Controller\\ClientsAuthenticator". Did you forget to add a use statement?');
    }
}
