<?php

namespace Container6uE3EtC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8gQQpadService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8gQQpad' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8gQQpad'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'authenticationUtils' => ['privates', 'security.authentication_utils', 'getSecurity_AuthenticationUtilsService', true],
            'authenticator' => ['privates', '.errored.C5e6Njj', NULL, 'Cannot determine controller argument for "App\\Controller\\ClientController::cleanDatabases()": the $authenticator argument is type-hinted with the non-existent class or interface: "App\\Controller\\ClientsAuthenticator". Did you forget to add a use statement?'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'userAuthenticator' => ['privates', 'security.user_authenticator', 'getSecurity_UserAuthenticatorService', true],
        ], [
            'authenticationUtils' => '?',
            'authenticator' => '?',
            'entityManager' => '?',
            'userAuthenticator' => '?',
        ]);
    }
}
