controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

#Page Accueil
index:
  path: /
  methods: ["GET", "POST"]
  controller: App\Controller\IndexController::index

#Script création nouveau client
creerClient:
  path: /creerClient
  methods: ["POST"]
  controller: App\Controller\ClientController::creerClient

#Script récupération photos
getPhotos:
  path: /getPhotos
  methods: ["POST"]
  controller: App\Controller\DropboxController::getPhotos

testDrobpox:
  path: /isFolderExists
  methods: ["POST"]
  controller: App\Controller\DropboxController::isFolderExists

linkAccess:
  path: '/vues/{id<\d{8}>}'
  controller: App\Controller\DropboxController::showPageVuesId

pageVues:
  path: "/trouver-une-visite"
  controller: App\Controller\DropboxController::showPageVues

getPhotoForm:
  path: "/getPhotoForm"
  controller: App\Controller\ClientController::getPhotoForm

connexionClient:
  path: "/getPhotoForm"
  controller: App\Controller\ClientController::connexionClient


dropbox_auth_start:
  path: /dropbox-auth-start

# Route pour la gestion des erreurs 404
error_404:
  path: /{wildcard}
  controller: App\Controller\ErrorPageController::error404
  requirements:
    wildcard: ".*"
