<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerONXmJUV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerONXmJUV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerONXmJUV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerONXmJUV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerONXmJUV\App_KernelDevDebugContainer([
    'container.build_hash' => 'ONXmJUV',
    'container.build_id' => '3b5ddc0e',
    'container.build_time' => 1710882850,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerONXmJUV');
