<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXrfat4k\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXrfat4k/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXrfat4k.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXrfat4k\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXrfat4k\App_KernelDevDebugContainer([
    'container.build_hash' => 'Xrfat4k',
    'container.build_id' => '383148a7',
    'container.build_time' => 1708126246,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXrfat4k');
