<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF9WFuty\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF9WFuty/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerF9WFuty.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerF9WFuty\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerF9WFuty\App_KernelDevDebugContainer([
    'container.build_hash' => 'F9WFuty',
    'container.build_id' => 'b8234a2c',
    'container.build_time' => 1709329354,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF9WFuty');
